deps: add `persistent_merkle_tree` to `int` tests (#42)
`zig` commands sometimes fail with

```
test/int/type/tree_view.zig:10:26: error: no module named 'persistent_merkle_tree' available within module root
    const Node = @import("persistent_merkle_tree").Node;
```

because of a missing import on the said module. My guess is this import
was manually added to `build.zig`, and `zbuild sync` deletes it when
run. This PR adds it to `zbuild.zon`.

Running `zbuild sync` also seems to have rearranged its position in
`build.zig`.